# Generated by Django 3.1 on 2020-09-18 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='user_id')),
                ('game_date', models.DateField(default=datetime.date.today, null=True, verbose_name='game_date')),
                ('game_name', models.CharField(max_length=30, null=True, verbose_name='game_name')),
                ('battle_division', models.IntegerField(choices=[(0, 'フリー'), (1, '公式')], null=True, verbose_name='battle_division')),
                ('my_title', models.CharField(max_length=50, null=True, verbose_name='my_title')),
                ('opp_title', models.CharField(max_length=50, null=True, verbose_name='opp_title')),
                ('frirst_strike', models.IntegerField(choices=[(0, '先攻'), (1, '後攻')], null=True, verbose_name='frirst_strike')),
                ('win_lose', models.IntegerField(choices=[(0, '勝利'), (1, '敗北')], null=True, verbose_name='win_lose')),
                ('game_score', models.IntegerField(blank=True, null=True, verbose_name='game_score')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='comment')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='update_date')),
            ],
            options={
                'verbose_name_plural': 'match_record',
                'db_table': 'match_record',
            },
        ),
    ]
